### ISSUE TITLE
Terminal cuts off long strings when debugging #21170

### ISSUE THREAD

**Issue by BigDreamDev** [BigDreamDev/Betting-Dashboard-Front#7]
Steps to reproduce:
Create a Python file with the following code that prints a 1MB string made of '0123456789' repeated 100.000 times:
print('\n'.join(['0123456789' for i in range(100_000)]))
print('finished')
Run with "Python: Debug Python file".
Note it only happens with "Debug Python file", not "Run Python file in Terminal".

**Comment by funnynight** [comment]
Diagnostic data
Python version (& distribution if applicable, e.g. Anaconda): 3.11.3
Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
Value of the python.languageServer setting: Default
Output for Python in the Output panel (View→Output, change the drop-down the upper-right of the Output panel to Python)
User Settings
Extension version: 2023.6.1
VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes
